# Site settings
title: Mark Anthony Navarro — Portfolio
description: Personal portfolio and blog. Projects, writings, and contact.
# Production URL for GitHub Pages user/org site
url: "https://max31337.github.io"
# Project site base path
baseurl: "/my-portfolio"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

# Exclude
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - feed.xml

# Author
author:
  name: Mark Anthony Navarro
  email: navarro.markanthony.tud@gmail.com
  socials:
    github: max31337
    linkedin: markanthonynavarro
